package social

var TownNames = []string{
	"Eisenbourg",
	"Verdantville",
	"Steinwalden",
	"Châteauverde",
	"Elmsburg",
	"Rosenfeld",
	"Brumeheim",
	"Silberwych",
	"Hügelstadt",
	"Blancbourg",
	"Amberwilde",
	"Thornsburg",
	"Eichental",
	"Fleurmont",
	"Graustead",
	"Larkenshire",
	"Silberschloss",
	"Leinfeld",
	"Eberwald",
	"Gildedorf",
	"Steinbrück",
	"Lumièreval",
	"Wittenburg",
	"Silberbach",
	"Rosenhafen",
}

var ExpeditionNames = []string{
	"Dragon's Roar",
	"Sea Serpent",
	"Iron Maiden",
	"Stormbringer",
	"Black Pearl",
	"Galleon's Fury",
	"Mystic Mermaid",
	"Viking Raider",
	"Crusader's Quest",
	"Wraith's Revenge",
	"Neptune's Trident",
	"Thunderclap",
	"Shadowhawk",
	"Tempestuous Maiden",
	"Corsair's Fortune",
	"Celestial Navigator",
	"Crimson Typhoon",
	"Moonlit Marauder",
	"Ghostly Galleon",
	"Leviathan's Legacy",
	"Sea Witch",
	"Dagger's Edge",
	"Plundering Pegasus",
	"Buccaneer's Pride",
	"Elusive Kraken",
}
