package social

var TownNames = []string{
	"Eisenbourg",
	"Verdantville",
	"Steinwalden",
	"Châteauverde",
	"Elmsburg",
	"Rosenfeld",
	"Brumeheim",
	"Silberwych",
	"Hügelstadt",
	"Blancbourg",
	"Amberwilde",
	"Thornsburg",
	"Eichental",
	"Fleurmont",
	"Graustead",
	"Larkenshire",
	"Silberschloss",
	"Leinfeld",
	"Eberwald",
	"Gildedorf",
	"Steinbrück",
	"Lumièreval",
	"Wittenburg",
	"Silberbach",
	"Rosenhafen",
}

var ExpeditionNames = []string{
	"Dragon's Roar",
	"Sea Serpent",
	"Iron Maiden",
	"Stormbringer",
	"Black Pearl",
	"Galleon's Fury",
	"Mystic Mermaid",
	"Viking Raider",
	"Crusader's Quest",
	"Wraith's Revenge",
	"Neptune's Trident",
	"Thunderclap",
	"Shadowhawk",
	"Tempestuous Maiden",
	"Corsair's Fortune",
	"Celestial Navigator",
	"Crimson Typhoon",
	"Moonlit Marauder",
	"Ghostly Galleon",
	"Leviathan's Legacy",
	"Sea Witch",
	"Dagger's Edge",
	"Plundering Pegasus",
	"Buccaneer's Pride",
	"Elusive Kraken",
}

var OutlawColonyNames = []string{
	"Thorn Haven",
	"Rusty Shack",
	"Wild Vipers",
	"Iron Hideout",
	"Black Serpents",
	"Blood Ravine",
	"Shadow Cliff",
	"Skull Cove",
	"Dusty Hideaway",
	"Grim Thicket",
	"Dagger Grove",
	"Bone Pit",
	"Midnight Den",
	"Lawless Lair",
	"Broken Trail",
	"Ghost Watch",
	"Marauder's Roost",
	"Rogue's Retreat",
	"Dark Canyon",
}
